use wasm_bindgen::prelude::*;
use serde::{Serialize, Deserialize};
use std::collections::HashMap;
use regex::Regex;

#[derive(Serialize, Deserialize)]
pub struct CompiledModule {
    pub code: String,
    pub exports: Vec<String>,
    pub modules: Vec<String>,
    pub errors: Vec<String>,
}

#[wasm_bindgen]
pub struct JovaCompiler {
    modules: HashMap<String, String>,
    exports: Vec<String>,
    custom_expressions: HashMap<String, String>,
}

#[wasm_bindgen]
impl JovaCompiler {
    #[wasm_bindgen(constructor)]
    pub fn new() -> JovaCompiler {
        JovaCompiler {
            modules: HashMap::new(),
            exports: Vec::new(),
            custom_expressions: HashMap::new(),
        }
    }
    
    pub fn compile(&mut self, source: &str) -> String {
        let result = self.compile_internal(source);
        serde_json::to_string(&result).unwrap()
    }
    
    fn compile_internal(&mut self, source: &str) -> CompiledModule {
        let mut output = String::new();
        let mut errors = Vec::new();
        
        output.push_str("// Generated by JOVA Compiler v2.3\n");
        output.push_str("(function() {\n");
        output.push_str("  const JOVA = window.JOVA || { modules: {}, languages: {}, customExpressions: {} };\n");
        output.push_str("  function jovaPrint(v) { console.log(v); return v; }\n");
        output.push_str("  const jovaString = {\n");
        output.push_str("    concat: function(a,b) { return String(a) + String(b); },\n");
        output.push_str("    upper: function(s) { return String(s).toUpperCase(); },\n");
        output.push_str("    lower: function(s) { return String(s).toLowerCase(); },\n");
        output.push_str("    len: function(s) { return String(s).length; },\n");
        output.push_str("    sub: function(s,start,end) { return String(s).substring(start,end); },\n");
        output.push_str("    replace: function(s,find,repl) { return String(s).replace(new RegExp(find,'g'), repl); },\n");
        output.push_str("    trim: function(s) { return String(s).trim(); },\n");
        output.push_str("    split: function(s,delim) { return String(s).split(delim); },\n");
        output.push_str("    at: function(s,index) { return String(s).charAt(index); }\n");
        output.push_str("  };\n");
        
        // Strip comments @@@ ... @@@
        let mut no_comments = String::new();
        let mut in_comment = false;
        let mut chars = source.chars().peekable();
        while let Some(c) = chars.next() {
            if !in_comment && c == '@' && chars.peek() == Some(&'@') && chars.clone().nth(1) == Some('@') {
                in_comment = true;
                chars.next(); chars.next();
                continue;
            }
            if in_comment && c == '@' && chars.peek() == Some(&'@') && chars.clone().nth(1) == Some('@') {
                in_comment = false;
                chars.next(); chars.next();
                continue;
            }
            if !in_comment {
                no_comments.push(c);
            }
        }
        
        let lines: Vec<&str> = no_comments.lines().collect();
        let mut i = 0;
        while i < lines.len() {
            let line = lines[i].trim();
            if line.is_empty() { i += 1; continue; }
            
            if line.starts_with("JOVA:") {
                let cmd_raw = (&line[5..]).trim();
                let cmd = cmd_raw.to_string();
                
                if cmd.starts_with("Import Pop") {
                    output.push_str("  console.log('[JOVA] Importing');\n");
                }
                else if cmd == "Export All Pops and Models" || cmd == "Export All Pops and Models." {
                    output.push_str("  // Exporting all modules\n");
                    let keys: Vec<String> = self.modules.keys().cloned().collect();
                    for name in keys {
                        output.push_str(&format!("  window.{} = JOVA.modules['{}'];\n", name, name));
                        self.exports.push(name);
                    }
                }
                else if cmd.starts_with("New Language") {
                    if let Some(caps) = Regex::new(r"New Language - (\w+)").unwrap().captures(&cmd) {
                        let lang_name = caps[1].to_string();
                        output.push_str(&format!("  JOVA.languages['{}'] = {{ created: new Date() }};\n", lang_name));
                        output.push_str(&format!("  window.{} = {{}};\n", lang_name));
                        self.modules.insert(lang_name, "language".to_string());
                    }
                }
                else if cmd.starts_with("express") {
                    let rest = &cmd["express".len()..].trim();
                    if let Some((name, def)) = rest.split_once(' ') {
                        let name = name.trim().to_string();
                        let definition = def.trim().to_string();
                        self.custom_expressions.insert(name.clone(), definition.clone());
                        output.push_str(&format!("  JOVA.customExpressions['{}'] = function() {{ return ({}); }};\n", name, definition));
                        output.push_str(&format!("  window.{} = JOVA.customExpressions['{}'];\n", name, name));
                    } else {
                        errors.push(format!("Invalid custom expression: {}", cmd));
                    }
                }
                else if cmd.starts_with("L ") {
                    let after_l = &cmd["L ".len()..].trim();
                    let (count_expr, inline_close) = if after_l.ends_with(')') {
                        (after_l[..after_l.len()-1].trim().to_string(), true)
                    } else {
                        (after_l.to_string(), false)
                    };
                    
                    let mut body_lines = Vec::new();
                    if !inline_close {
                        i += 1;
                        while i < lines.len() && lines[i].trim() != ")" {
                            body_lines.push(lines[i].trim());
                            i += 1;
                        }
                        if i >= lines.len() {
                            errors.push("Unclosed loop: missing ')'".to_string());
                            break;
                        }
                    }
                    let js_count = self.transform_expression(&count_expr);
                    let mut js_body = String::new();
                    for bline in body_lines {
                        js_body.push_str(&self.transform_line(bline));
                        js_body.push('\n');
                    }
                    output.push_str(&format!("  for (let _i = 0; _i < ({}); _i++) {{\n{}}}\n", js_count, js_body));
                    if inline_close { i += 1; } else { i += 1; }
                    continue;
                }
            }
            else if line.starts_with("Pop:") {
                let stmt = (&line[4..]).trim().to_string();
                if stmt.starts_with("New module") {
                    if let Some(caps) = Regex::new(r"New module - (\w+) - (\w+) (\d+)").unwrap().captures(&stmt) {
                        let name = caps[1].to_string();
                        let value = caps[3].to_string();
                        output.push_str(&format!("  JOVA.modules['{}'] = {{ value: {} }};\n", name, value));
                        output.push_str(&format!("  window.{} = JOVA.modules['{}'];\n", name, name));
                        self.modules.insert(name, value);
                    } else {
                        let parts: Vec<&str> = stmt.split_whitespace().collect();
                        if parts.len() >= 4 {
                            let name = parts[2];
                            let value = parts[4];
                            output.push_str(&format!("  JOVA.modules['{}'] = {{ value: '{}' }};\n", name, value));
                            self.modules.insert(name.to_string(), value.to_string());
                        }
                    }
                }
            }
            else if line.starts_with("P:") {
                let to_print = (&line[2..]).trim();
                let js_expr = self.transform_expression(to_print);
                output.push_str(&format!("  jovaPrint({});\n", js_expr));
            }
            else if line.contains('-') && !line.starts_with("JOVA:") && !line.starts_with("Pop:") {
                let parts: Vec<&str> = line.split('-').collect();
                if parts.len() >= 2 {
                    let var_name = parts[0].trim();
                    let var_value = parts[1].trim();
                    let js_value = self.transform_expression(var_value);
                    output.push_str(&format!("  const {} = {};\n", var_name, js_value));
                }
            }
            else {
                errors.push(format!("Unknown syntax: {}", line));
            }
            i += 1;
        }
        
        output.push_str("  window.JOVA = JOVA;\n  console.log('[JOVA] Execution complete');\n})();\n");
        CompiledModule {
            code: output,
            exports: self.exports.clone(),
            modules: self.modules.keys().cloned().collect(),
            errors,
        }
    }
    
    fn transform_line(&self, line: &str) -> String {
        if line.starts_with("P:") {
            let expr = self.transform_expression(&line[2..].trim());
            format!("    jovaPrint({});", expr)
        } else if line.contains('-') && !line.starts_with("JOVA:") && !line.starts_with("Pop:") {
            let parts: Vec<&str> = line.split('-').collect();
            if parts.len() >= 2 {
                let var_name = parts[0].trim();
                let var_value = parts[1].trim();
                let js_value = self.transform_expression(var_value);
                format!("    const {} = {};", var_name, js_value)
            } else {
                format!("    {};", self.transform_expression(line))
            }
        } else {
            format!("    {};", self.transform_expression(line))
        }
    }
    
    fn transform_expression(&self, expr: &str) -> String {
        let expr = expr.trim();
        
        // CUSTOM EXPRESSION
        if self.custom_expressions.contains_key(expr) {
            return format!("JOVA.customExpressions['{}']()", expr);
        }
        
        // STRING OPERATIONS: $operations$
        if expr.starts_with('$') && expr.ends_with('$') {
            let inner = &expr[1..expr.len()-1];
            return self.transform_string_operations(inner);
        }
        
        // CONDITIONAL (IF ... THEN ... ELSE ...)
        if let Some(caps) = Regex::new(r"(?i)^\(IF\s+(.+?)\s+THEN\s+(.+?)\s+ELSE\s+(.+)\)$").unwrap().captures(expr) {
            let cond = self.transform_expression(caps[1].trim());
            let true_expr = self.transform_expression(caps[2].trim());
            let false_expr = self.transform_expression(caps[3].trim());
            return format!("({} ? {} : {})", cond, true_expr, false_expr);
        }
        
        // EQ OPERATOR
        let eq_re = Regex::new(r"^(.+)\s+EQ\s+(.+)$").unwrap();
        if let Some(caps) = eq_re.captures(expr) {
            let left = self.transform_expression(caps[1].trim());
            let right = self.transform_expression(caps[2].trim());
            return format!("({} === {})", left, right);
        }
        
        // STRING LITERAL
        if expr.starts_with('"') && expr.ends_with('"') {
            return expr.to_string();
        }
        
        // NUMBER
        if expr.parse::<f64>().is_ok() {
            return expr.to_string();
        }
        
        // BOOLEAN
        if expr == "true" || expr == "false" {
            return expr.to_string();
        }
        
        // ARITHMETIC
        if let Some(caps) = Regex::new(r"^(\w+)\s*([+\-*/%])\s*(\w+)$").unwrap().captures(expr) {
            let left = self.transform_expression(caps[1].trim());
            let op = caps[2].trim();
            let right = self.transform_expression(caps[3].trim());
            return format!("{} {} {}", left, op, right);
        }
        
        // COMPARISONS
        if let Some(caps) = Regex::new(r"^(\w+)\s*(==|!=|<=|>=|<|>)\s*(\w+)$").unwrap().captures(expr) {
            let left = self.transform_expression(caps[1].trim());
            let op = caps[2].trim();
            let right = self.transform_expression(caps[3].trim());
            return format!("{} {} {}", left, op, right);
        }
        
        // FUNCTION CALL
        if let Some(caps) = Regex::new(r"^(\w+)\((.*)\)$").unwrap().captures(expr) {
            let func = caps[1].to_string();
            let args = caps[2].split(',').map(|a| self.transform_expression(a.trim())).collect::<Vec<_>>().join(", ");
            return format!("{}({})", func, args);
        }
        
        // VARIABLE
        expr.to_string()
    }
    
    // NEW: Transform string operations inside $...$
    fn transform_string_operations(&self, ops: &str) -> String {
        let ops = ops.trim();
        
        // Pattern: concat(str1, str2)
        if let Some(caps) = Regex::new(r"^concat\((.+),\s*(.+)\)$").unwrap().captures(ops) {
            let a = self.transform_expression(caps[1].trim());
            let b = self.transform_expression(caps[2].trim());
            return format!("jovaString.concat({}, {})", a, b);
        }
        
        // Pattern: upper(str)
        if let Some(caps) = Regex::new(r"^upper\((.+)\)$").unwrap().captures(ops) {
            let s = self.transform_expression(caps[1].trim());
            return format!("jovaString.upper({})", s);
        }
        
        // Pattern: lower(str)
        if let Some(caps) = Regex::new(r"^lower\((.+)\)$").unwrap().captures(ops) {
            let s = self.transform_expression(caps[1].trim());
            return format!("jovaString.lower({})", s);
        }
        
        // Pattern: len(str)
        if let Some(caps) = Regex::new(r"^len\((.+)\)$").unwrap().captures(ops) {
            let s = self.transform_expression(caps[1].trim());
            return format!("jovaString.len({})", s);
        }
        
        // Pattern: sub(str, start, end)
        if let Some(caps) = Regex::new(r"^sub\((.+),\s*(\d+),\s*(\d+)\)$").unwrap().captures(ops) {
            let s = self.transform_expression(caps[1].trim());
            let start = caps[2].to_string();
            let end = caps[3].to_string();
            return format!("jovaString.sub({}, {}, {})", s, start, end);
        }
        
        // Pattern: replace(str, find, replace)
        if let Some(caps) = Regex::new(r"^replace\((.+),\s*(.+),\s*(.+)\)$").unwrap().captures(ops) {
            let s = self.transform_expression(caps[1].trim());
            let find = self.transform_expression(caps[2].trim());
            let repl = self.transform_expression(caps[3].trim());
            return format!("jovaString.replace({}, {}, {})", s, find, repl);
        }
        
        // Pattern: trim(str)
        if let Some(caps) = Regex::new(r"^trim\((.+)\)$").unwrap().captures(ops) {
            let s = self.transform_expression(caps[1].trim());
            return format!("jovaString.trim({})", s);
        }
        
        // Pattern: split(str, delim)
        if let Some(caps) = Regex::new(r"^split\((.+),\s*(.+)\)$").unwrap().captures(ops) {
            let s = self.transform_expression(caps[1].trim());
            let delim = self.transform_expression(caps[2].trim());
            return format!("jovaString.split({}, {})", s, delim);
        }
        
        // Pattern: at(str, index)
        if let Some(caps) = Regex::new(r"^at\((.+),\s*(\d+)\)$").unwrap().captures(ops) {
            let s = self.transform_expression(caps[1].trim());
            let idx = caps[2].to_string();
            return format!("jovaString.at({}, {})", s, idx);
        }
        
        // If no pattern matches, treat as literal string
        format!("\"{}\"", ops.replace('\\', "\\\\").replace('"', "\\\""))
    }
    
    pub fn get_modules(&self) -> String {
        format!("{:?}", self.modules.keys().collect::<Vec<_>>())
    }
    
    pub fn get_exports(&self) -> String {
        format!("{:?}", self.exports)
    }
}

impl Default for JovaCompiler {
    fn default() -> Self {
        Self::new()
    }
}
