use wasm_bindgen::prelude::*;
use serde::{Serialize, Deserialize};
use std::collections::HashMap;
use regex::Regex;

#[derive(Serialize, Deserialize)]
pub struct CompiledModule {
    pub code: String,
    pub exports: Vec<String>,
    pub modules: Vec<String>,
    pub errors: Vec<String>,
}

#[wasm_bindgen]
pub struct JovaCompiler {
    modules: HashMap<String, String>,
    exports: Vec<String>,
}

#[wasm_bindgen]
impl JovaCompiler {
    #[wasm_bindgen(constructor)]
    pub fn new() -> JovaCompiler {
        JovaCompiler {
            modules: HashMap::new(),
            exports: Vec::new(),
        }
    }
    
    pub fn compile(&mut self, source: &str) -> String {
        let result = self.compile_internal(source);
        serde_json::to_string(&result).unwrap()
    }
    
    fn compile_internal(&mut self, source: &str) -> CompiledModule {
        let mut output = String::new();
        let mut errors = Vec::new();
        
        output.push_str("// Generated by JOVA Compiler v1.0\n");
        output.push_str("// Runtime initialized\n\n");
        output.push_str("(function() {\n");
        output.push_str("  const JOVA = window.JOVA || {};\n\n");
        
        let lines: Vec<&str> = source.lines().collect();
        let mut i = 0;
        
        while i < lines.len() {
            let line = lines[i].trim();
            
            if line.is_empty() || line.starts_with("//") {
                i += 1;
                continue;
            }
            
            // Parse JOVA: commands
            if line.starts_with("JOVA:") {
                let cmd = &line[5..].trim();
                
                if cmd.starts_with("Import Pop") {
                    output.push_str(&format!("  // Importing modules\n"));
                    output.push_str(&format!("  console.log('[JOVA] Importing');\n"));
                }
                else if cmd == "Export All Pops and Models" || cmd == "Export All Pops and Models." {
                    output.push_str(&format!("  // Exporting all modules\n"));
                    for name in self.modules.keys() {
                        output.push_str(&format!("  window.{} = JOVA.modules['{}'];\n", name, name));
                        self.exports.push(name.clone());
                    }
                }
                else if cmd.starts_with("New Language") {
                    let re = Regex::new(r"New Language - (\w+)").unwrap();
                    if let Some(caps) = re.captures(cmd) {
                        let lang_name = caps[1].to_string();
                        output.push_str(&format!("  // Creating new language: {}\n", lang_name));
                        output.push_str(&format!("  JOVA.languages['{}'] = {{ created: new Date() }};\n", lang_name));
                        output.push_str(&format!("  window.{} = {{}};\n", lang_name));
                        self.modules.insert(lang_name.clone(), "language".to_string());
                    }
                }
            }
            
            // Parse Pop: statements
            else if line.starts_with("Pop:") {
                let stmt = &line[4..].trim();
                
                if stmt.starts_with("New module") {
                    let re = Regex::new(r"New module - (\w+) - (\w+) (\d+)").unwrap();
                    if let Some(caps) = re.captures(stmt) {
                        let name = caps[1].to_string();
                        let type_name = caps[2].to_string();
                        let value = caps[3].to_string();
                        
                        output.push_str(&format!("  // Creating module: {}\n", name));
                        output.push_str(&format!("  JOVA.modules['{}'] = {{ type: '{}', value: {} }};\n", name, type_name, value));
                        output.push_str(&format!("  window.{} = JOVA.modules['{}'];\n", name, name));
                        self.modules.insert(name, value);
                    } else {
                        // Fallback for different format
                        let parts: Vec<&str> = stmt.split_whitespace().collect();
                        if parts.len() >= 4 {
                            let name = parts[2];
                            let value = parts[4];
                            output.push_str(&format!("  // Creating module: {}\n", name));
                            output.push_str(&format!("  JOVA.modules['{}'] = {{ value: '{}' }};\n", name, value));
                            self.modules.insert(name.to_string(), value.to_string());
                        }
                    }
                }
            }
            
            // Parse inline assignments
            else if line.contains('-') && !line.starts_with("JOVA:") && !line.starts_with("Pop:") {
                let parts: Vec<&str> = line.split('-').collect();
                if parts.len() >= 2 {
                    let var_name = parts[0].trim();
                    let var_value = parts[1].trim();
                    output.push_str(&format!("  const {} = {};\n", var_name, var_value));
                }
            }
            
            i += 1;
        }
        
        output.push_str("\n  // Runtime helpers\n");
        output.push_str("  window.JOVA = window.JOVA || { modules: {}, languages: {} };\n");
        output.push_str("  console.log('[JOVA] Execution complete');\n");
        output.push_str("})();\n");
        
        CompiledModule {
            code: output,
            exports: self.exports.clone(),
            modules: self.modules.keys().cloned().collect(),
            errors,
        }
    }
    
    pub fn get_modules(&self) -> String {
        format!("{:?}", self.modules.keys().collect::<Vec<_>>())
    }
    
    pub fn get_exports(&self) -> String {
        format!("{:?}", self.exports)
    }
}

impl Default for JovaCompiler {
    fn default() -> Self {
        Self::new()
    }
}
