use wasm_bindgen::prelude::*;
use serde::{Serialize, Deserialize};
use std::collections::HashMap;
use std::fs;
use std::path::Path;
use regex::Regex;

#[derive(Serialize, Deserialize)]
pub struct CompiledModule {
    pub code: String,
    pub exports: Vec<String>,
    pub modules: Vec<String>,
    pub errors: Vec<String>,
}

#[wasm_bindgen]
pub struct JovaCompiler {
    modules: HashMap<String, serde_json::Value>,
    exports: Vec<String>,
    custom_expressions: HashMap<String, (Vec<String>, String)>,
    objectives: HashMap<String, HashMap<String, String>>,
    arrays: HashMap<String, Vec<serde_json::Value>>,
    base_path: String,
}

#[wasm_bindgen]
impl JovaCompiler {
    #[wasm_bindgen(constructor)]
    pub fn new() -> JovaCompiler {
        JovaCompiler {
            modules: HashMap::new(),
            exports: Vec::new(),
            custom_expressions: HashMap::new(),
            objectives: HashMap::new(),
            arrays: HashMap::new(),
            base_path: std::env::current_dir().unwrap_or_default().to_string_lossy().to_string(),
        }
    }

    pub fn set_base_path(&mut self, path: &str) {
        self.base_path = path.to_string();
    }

    pub fn compile(&mut self, source: &str) -> String {
        let result = self.compile_internal(source);
        serde_json::to_string(&result).unwrap()
    }

    fn compile_internal(&mut self, source: &str) -> CompiledModule {
        let mut output = String::new();
        let mut errors = Vec::new();

        output.push_str("// Generated by JOVA Compiler v3.0 - Complete Implementation\n");
        output.push_str("(function() {\n");
        output.push_str("  const JOVA = window.JOVA || { modules: {}, languages: {}, customExpressions: {}, objectives: {}, arrays: {} };\n");
        output.push_str("  function jovaPrint(v) { console.log(v); return v; }\n");
        output.push_str("  const jovaString = {\n");
        output.push_str("    concat: function(a,b) { return String(a) + String(b); },\n");
        output.push_str("    upper: function(s) { return String(s).toUpperCase(); },\n");
        output.push_str("    lower: function(s) { return String(s).toLowerCase(); },\n");
        output.push_str("    len: function(s) { return String(s).length; },\n");
        output.push_str("    sub: function(s,start,end) { return String(s).substring(start,end); },\n");
        output.push_str("    replace: function(s,find,repl) { return String(s).replace(new RegExp(find,'g'), repl); },\n");
        output.push_str("    trim: function(s) { return String(s).trim(); },\n");
        output.push_str("    split: function(s,delim) { return String(s).split(delim); },\n");
        output.push_str("    at: function(s,index) { return String(s).charAt(index); }\n");
        output.push_str("  };\n");
        output.push_str("  const jovaArray = {\n");
        output.push_str("    push: function(arr,item) { arr.push(item); return arr; },\n");
        output.push_str("    pop: function(arr) { return arr.pop(); },\n");
        output.push_str("    shift: function(arr) { return arr.shift(); },\n");
        output.push_str("    unshift: function(arr,item) { arr.unshift(item); return arr; },\n");
        output.push_str("    length: function(arr) { return arr.length; },\n");
        output.push_str("    get: function(arr,idx) { return arr[idx]; },\n");
        output.push_str("    set: function(arr,idx,val) { arr[idx] = val; return arr; },\n");
        output.push_str("    slice: function(arr,start,end) { return arr.slice(start,end); },\n");
        output.push_str("    join: function(arr,sep) { return arr.join(sep); },\n");
        output.push_str("    map: function(arr,fn) { return arr.map(fn); },\n");
        output.push_str("    filter: function(arr,fn) { return arr.filter(fn); },\n");
        output.push_str("    reduce: function(arr,fn,init) { return arr.reduce(fn,init); }\n");
        output.push_str("  };\n");

        // Strip comments @@@ ... @@@
        let mut no_comments = String::new();
        let mut in_comment = false;
        let mut chars = source.chars().peekable();
        while let Some(c) = chars.next() {
            if !in_comment && c == '@' && chars.peek() == Some(&'@') && chars.clone().nth(1) == Some('@') {
                in_comment = true;
                chars.next(); chars.next();
                continue;
            }
            if in_comment && c == '@' && chars.peek() == Some(&'@') && chars.clone().nth(1) == Some('@') {
                in_comment = false;
                chars.next(); chars.next();
                continue;
            }
            if !in_comment {
                no_comments.push(c);
            }
        }

        let lines: Vec<&str> = no_comments.lines().collect();
        let mut i = 0;
        while i < lines.len() {
            let line = lines[i].trim();
            if line.is_empty() {
                i += 1;
                continue;
            }

            if line.starts_with("JOVA:") {
                let cmd_raw = (&line[5..]).trim();
                let cmd = cmd_raw.to_string();

                if cmd.starts_with("Import Pop") {
                    output.push_str("  console.log('[JOVA] Importing');\n");
                } else if cmd == "Export All Pops and Models" || cmd == "Export All Pops and Models." {
                    output.push_str("  // Exporting all modules\n");
                    let keys: Vec<String> = self.modules.keys().cloned().collect();
                    for name in keys {
                        let val = self.modules.get(&name).unwrap();
                        output.push_str(&format!("  JOVA.modules['{}'] = {};\n", name, val));
                        output.push_str(&format!("  window.{} = JOVA.modules['{}'];\n", name, name));
                        self.exports.push(name);
                    }
                    let obj_keys: Vec<String> = self.objectives.keys().cloned().collect();
                    for name in obj_keys {
                        output.push_str(&format!("  JOVA.objectives['{}'] = {{\n", name));
                        let obj = self.objectives.get(&name).unwrap();
                        for (k, v) in obj {
                            output.push_str(&format!("    {}: `{}`,\n", k, v));
                        }
                        output.push_str("  };\n");
                        output.push_str(&format!("  window.{} = JOVA.objectives['{}'];\n", name, name));
                        self.exports.push(name);
                    }
                    let arr_keys: Vec<String> = self.arrays.keys().cloned().collect();
                    for name in arr_keys {
                        let arr_val = self.arrays.get(&name).unwrap();
                        output.push_str(&format!("  JOVA.arrays['{}'] = {};\n", name, serde_json::to_string(arr_val).unwrap()));
                        output.push_str(&format!("  window.{} = JOVA.arrays['{}'];\n", name, name));
                        self.exports.push(name);
                    }
                } else if cmd.starts_with("New Language") {
                    if let Some(caps) = Regex::new(r"New Language - (\w+)").unwrap().captures(&cmd) {
                        let lang_name = caps[1].to_string();
                        output.push_str(&format!("  JOVA.languages['{}'] = {{ created: new Date() }};\n", lang_name));
                        output.push_str(&format!("  window.{} = {{}};\n", lang_name));
                        self.modules.insert(lang_name, serde_json::Value::String("language".to_string()));
                    }
                } else if cmd.starts_with("express") {
                    let rest = &cmd["express".len()..].trim();
                    if let Some((name, def)) = rest.split_once(' ') {
                        let name = name.trim().to_string();
                        let definition = def.trim().to_string();
                        let (params, body) = self.parse_expression_definition(&definition);
                        self.custom_expressions.insert(name.clone(), (params.clone(), body.clone()));
                        output.push_str(&format!(
                            "  JOVA.customExpressions['{}'] = function({}) {{ return ({}); }};\n",
                            name,
                            params.join(", "),
                            body
                        ));
                        output.push_str(&format!("  window.{} = JOVA.customExpressions['{}'];\n", name, name));
                    } else {
                        errors.push(format!("Invalid custom expression: {}", cmd));
                    }
                } else if cmd.starts_with("L ") {
                    let after_l = &cmd["L ".len()..].trim();
                    let (count_expr, inline_close) = if after_l.ends_with(')') {
                        (after_l[..after_l.len() - 1].trim().to_string(), true)
                    } else {
                        (after_l.to_string(), false)
                    };

                    let mut body_lines = Vec::new();
                    if !inline_close {
                        i += 1;
                        while i < lines.len() && lines[i].trim() != ")" {
                            body_lines.push(lines[i].trim());
                            i += 1;
                        }
                        if i >= lines.len() {
                            errors.push("Unclosed loop: missing ')'".to_string());
                            break;
                        }
                    }
                    let js_count = self.transform_expression(&count_expr);
                    let mut js_body = String::new();
                    for bline in body_lines {
                        js_body.push_str(&self.transform_line(bline));
                        js_body.push('\n');
                    }
                    output.push_str(&format!("  for (let _i = 0; _i < ({}); _i++) {{\n{}}}\n", js_count, js_body));
                    i += 1;
                    continue;
                }
            } else if line.starts_with("Pop:") {
                let stmt = (&line[4..]).trim().to_string();
                if stmt.starts_with("New module") {
                    if stmt.contains("objective {") {
                        let re = Regex::new(r"New module - (\w+) - objective \{([\s\S]*)\}").unwrap();
                        if let Some(caps) = re.captures(&stmt) {
                            let name = caps[1].to_string();
                            let content = caps[2].to_string();
                            let mut obj_map = HashMap::new();
                            for upload_line in content.lines() {
                                let single_pattern = r#"(\w+):\s*upload\("(.+)"\)"#;
                                if let Some(upload_caps) = Regex::new(single_pattern).unwrap().captures(upload_line) {
                                    let key = upload_caps[1].to_string();
                                    let path = upload_caps[2].to_string();
                                    let full_path = Path::new(&self.base_path).join(&path);
                                    let file_content = if full_path.exists() {
                                        fs::read_to_string(&full_path).unwrap_or_else(|_| format!("[ERROR: Could not read {}]", path))
                                    } else {
                                        format!("[ERROR: File not found: {}]", path)
                                    };
                                    obj_map.insert(key, file_content);
                                }
                                let dir_pattern = r#"(\w+):\s*upload_all\("(.+)"\)"#;
                                if let Some(upload_all_caps) = Regex::new(dir_pattern).unwrap().captures(upload_line) {
                                    let key = upload_all_caps[1].to_string();
                                    let path = upload_all_caps[2].to_string();
                                    let full_path = Path::new(&self.base_path).join(&path);
                                    let mut dir_contents = HashMap::new();
                                    if full_path.exists() && full_path.is_dir() {
                                        for entry in fs::read_dir(&full_path).unwrap_or_default() {
                                            if let Ok(entry) = entry {
                                                let file_name = entry.file_name().to_string_lossy().to_string();
                                                if let Ok(content) = fs::read_to_string(entry.path()) {
                                                    dir_contents.insert(file_name, content);
                                                }
                                            }
                                        }
                                    }
                                    obj_map.insert(key, serde_json::to_string(&dir_contents).unwrap_or_default());
                                }
                            }
                            self.objectives.insert(name.clone(), obj_map.clone());
                            output.push_str(&format!("  JOVA.objectives['{}'] = {{\n", name));
                            for (k, v) in obj_map {
                                let escaped = v.replace('`', "\\`").replace('$', "\\$");
                                output.push_str(&format!("    {}: `{}`,\n", k, escaped));
                            }
                            output.push_str("  };\n");
                            output.push_str(&format!("  window.{} = JOVA.objectives['{}'];\n", name, name));
                        }
                    } else if stmt.contains("value [") && stmt.contains("]") {
                        let re = Regex::new(r"New module - (\w+) - value \[(.*)\]").unwrap();
                        if let Some(caps) = re.captures(&stmt) {
                            let name = caps[1].to_string();
                            let array_str = caps[2].to_string();
                            let elements: Vec<String> = array_str.split(',').map(|s| s.trim().to_string()).collect();
                            let json_elements: Vec<serde_json::Value> = elements
                                .iter()
                                .map(|e| {
                                    if e.starts_with('"') {
                                        serde_json::Value::String(e.trim_matches('"').to_string())
                                    } else if e.parse::<i64>().is_ok() {
                                        serde_json::Value::Number(e.parse().unwrap())
                                    } else if e == "true" {
                                        serde_json::Value::Bool(true)
                                    } else if e == "false" {
                                        serde_json::Value::Bool(false)
                                    } else {
                                        serde_json::Value::String(e.clone())
                                    }
                                })
                                .collect();
                            self.arrays.insert(name.clone(), json_elements.clone());
                            output.push_str(&format!("  JOVA.arrays['{}'] = {};\n", name, serde_json::to_string(&json_elements).unwrap()));
                            output.push_str(&format!("  window.{} = JOVA.arrays['{}'];\n", name, name));
                        }
                    } else if let Some(caps) = Regex::new(r"New module - (\w+) - value (.+)").unwrap().captures(&stmt) {
                        let name = caps[1].to_string();
                        let value = caps[2].to_string();
                        let parsed = self.parse_json_value(&value);
                        self.modules.insert(name.clone(), parsed.clone());
                        output.push_str(&format!("  JOVA.modules['{}'] = {};\n", name, parsed));
                        output.push_str(&format!("  window.{} = JOVA.modules['{}'];\n", name, name));
                    } else {
                        let parts: Vec<&str> = stmt.split_whitespace().collect();
                        if parts.len() >= 4 {
                            let name = parts[2];
                            let value = parts[4];
                            self.modules.insert(name.to_string(), serde_json::Value::String(value.to_string()));
                            output.push_str(&format!("  JOVA.modules['{}'] = {{ value: '{}' }};\n", name, value));
                        }
                    }
                }
            } else if line.starts_with("P:") {
                let to_print = (&line[2..]).trim();
                let js_expr = self.transform_expression(to_print);
                output.push_str(&format!("  jovaPrint({});\n", js_expr));
            } else if line.contains('-') && !line.starts_with("JOVA:") && !line.starts_with("Pop:") {
                let parts: Vec<&str> = line.split('-').collect();
                if parts.len() >= 2 {
                    let var_name = parts[0].trim();
                    let var_value = parts[1].trim();
                    let js_value = self.transform_expression(var_value);
                    output.push_str(&format!("  const {} = {};\n", var_name, js_value));
                }
            } else {
                errors.push(format!("Unknown syntax: {}", line));
            }
            i += 1;
        }

        output.push_str("  window.JOVA = JOVA;\n  console.log('[JOVA] Execution complete');\n})();\n");
        CompiledModule {
            code: output,
            exports: self.exports.clone(),
            modules: self.modules.keys().cloned().collect(),
            errors,
        }
    }

    fn parse_expression_definition(&self, def: &str) -> (Vec<String>, String) {
        let parts: Vec<&str> = def.split_whitespace().collect();
        let mut params = Vec::new();
        let mut body_parts = Vec::new();

        for part in parts {
            if part.starts_with(':') && part.ends_with(':') {
                let param_name = &part[1..part.len() - 1];
                params.push(param_name.to_string());
                body_parts.push(param_name.to_string());
            } else if part == ":+:" {
                body_parts.push("+".to_string());
            } else if part == ":-:" {
                body_parts.push("-".to_string());
            } else if part == ":*:" {
                body_parts.push("*".to_string());
            } else if part == ":/:" {
                body_parts.push("/".to_string());
            } else if part == ":%:" {
                body_parts.push("%".to_string());
            } else if part == ":EQ:" {
                body_parts.push("===".to_string());
            } else if part == ":NE:" {
                body_parts.push("!==".to_string());
            } else if part == ":GT:" {
                body_parts.push(">".to_string());
            } else if part == ":LT:" {
                body_parts.push("<".to_string());
            } else if part == ":GE:" {
                body_parts.push(">=".to_string());
            } else if part == ":LE:" {
                body_parts.push("<=".to_string());
            } else if part == ":AND:" {
                body_parts.push("&&".to_string());
            } else if part == ":OR:" {
                body_parts.push("||".to_string());
            } else if part == ":NOT:" {
                body_parts.push("!".to_string());
            } else {
                body_parts.push(part.to_string());
            }
        }
        (params, body_parts.join(" "))
    }

    fn parse_json_value(&self, val: &str) -> serde_json::Value {
        let val = val.trim();
        if val.starts_with('"') && val.ends_with('"') {
            serde_json::Value::String(val[1..val.len() - 1].to_string())
        } else if val == "true" {
            serde_json::Value::Bool(true)
        } else if val == "false" {
            serde_json::Value::Bool(false)
        } else if let Ok(num) = val.parse::<i64>() {
            serde_json::Value::Number(num.into())
        } else if let Ok(num) = val.parse::<f64>() {
            serde_json::Number::from_f64(num).map_or(serde_json::Value::String(val.to_string()), serde_json::Value::Number)
        } else {
            serde_json::Value::String(val.to_string())
        }
    }

    fn transform_line(&self, line: &str) -> String {
        if line.starts_with("P:") {
            let expr = self.transform_expression(&line[2..].trim());
            format!("    jovaPrint({});", expr)
        } else if line.contains('-') && !line.starts_with("JOVA:") && !line.starts_with("Pop:") {
            let parts: Vec<&str> = line.split('-').collect();
            if parts.len() >= 2 {
                let var_name = parts[0].trim();
                let var_value = parts[1].trim();
                let js_value = self.transform_expression(var_value);
                format!("    const {} = {};", var_name, js_value)
            } else {
                format!("    {};", self.transform_expression(line))
            }
        } else {
            format!("    {};", self.transform_expression(line))
        }
    }

    fn transform_expression(&self, expr: &str) -> String {
        let expr = expr.trim();

        if let Some(caps) = Regex::new(r"^(\w+)\[(\d+)\]$").unwrap().captures(expr) {
            let arr_name = caps[1].to_string();
            let idx = caps[2].to_string();
            return format!("jovaArray.get({}, {})", arr_name, idx);
        }
        if let Some(caps) = Regex::new(r"^push\((\w+),\s*(.+)\)$").unwrap().captures(expr) {
            let arr = caps[1].to_string();
            let item = self.transform_expression(caps[2].trim());
            return format!("jovaArray.push({}, {})", arr, item);
        }
        if let Some(caps) = Regex::new(r"^pop\((\w+)\)$").unwrap().captures(expr) {
            let arr = caps[1].to_string();
            return format!("jovaArray.pop({})", arr);
        }
        if let Some(caps) = Regex::new(r"^len\((\w+)\)$").unwrap().captures(expr) {
            let arr = caps[1].to_string();
            return format!("jovaArray.length({})", arr);
        }
        if self.custom_expressions.contains_key(expr) {
            return format!("JOVA.customExpressions['{}']()", expr);
        }
        if expr.starts_with('$') && expr.ends_with('$') {
            let inner = &expr[1..expr.len() - 1];
            return self.transform_string_operations(inner);
        }
        if let Some(caps) = Regex::new(r"(?i)^\(IF\s+(.+?)\s+THEN\s+(.+?)\s+ELSE\s+(.+)\)$").unwrap().captures(expr) {
            let cond = self.transform_expression(caps[1].trim());
            let true_expr = self.transform_expression(caps[2].trim());
            let false_expr = self.transform_expression(caps[3].trim());
            return format!("({} ? {} : {})", cond, true_expr, false_expr);
        }
        let ops = [("EQ", "==="), ("NE", "!=="), ("GT", ">"), ("LT", "<"), ("GE", ">="), ("LE", "<=")];
        for (jova_op, js_op) in ops {
            let re = Regex::new(&format!(r"^(.+)\s+{}\s+(.+)$", jova_op)).unwrap();
            if let Some(caps) = re.captures(expr) {
                let left = self.transform_expression(caps[1].trim());
                let right = self.transform_expression(caps[2].trim());
                return format!("({} {} {})", left, js_op, right);
            }
        }
        if let Some(caps) = Regex::new(r"^(.+)\s+AND\s+(.+)$").unwrap().captures(expr) {
            let left = self.transform_expression(caps[1].trim());
            let right = self.transform_expression(caps[2].trim());
            return format!("({} && {})", left, right);
        }
        if let Some(caps) = Regex::new(r"^(.+)\s+OR\s+(.+)$").unwrap().captures(expr) {
            let left = self.transform_expression(caps[1].trim());
            let right = self.transform_expression(caps[2].trim());
            return format!("({} || {})", left, right);
        }
        if let Some(caps) = Regex::new(r"^NOT\s+(.+)$").unwrap().captures(expr) {
            let inner = self.transform_expression(caps[1].trim());
            return format!("(!{})", inner);
        }
        if expr.starts_with('"') && expr.ends_with('"') {
            return expr.to_string();
        }
        if expr.parse::<f64>().is_ok() {
            return expr.to_string();
        }
        if expr == "true" || expr == "false" {
            return expr.to_string();
        }
        if let Some(caps) = Regex::new(r"^(\w+)\s*([+\-*/%])\s*(\w+)$").unwrap().captures(expr) {
            let left = self.transform_expression(caps[1].trim());
            let op = caps[2].trim();
            let right = self.transform_expression(caps[3].trim());
            return format!("{} {} {}", left, op, right);
        }
        if let Some(caps) = Regex::new(r"^(\w+)\s*(==|!=|<=|>=|<|>)\s*(\w+)$").unwrap().captures(expr) {
            let left = self.transform_expression(caps[1].trim());
            let op = caps[2].trim();
            let right = self.transform_expression(caps[3].trim());
            return format!("{} {} {}", left, op, right);
        }
        if let Some(caps) = Regex::new(r"^(\w+)\((.*)\)$").unwrap().captures(expr) {
            let func = caps[1].to_string();
            let args = caps[2].split(',').map(|a| self.transform_expression(a.trim())).collect::<Vec<_>>().join(", ");
            return format!("{}({})", func, args);
        }
        expr.to_string()
    }

    fn transform_string_operations(&self, ops: &str) -> String {
        let ops = ops.trim();
        let patterns = [
            (r"^concat\((.+),\s*(.+)\)$", "jovaString.concat({}, {})"),
            (r"^upper\((.+)\)$", "jovaString.upper({})"),
            (r"^lower\((.+)\)$", "jovaString.lower({})"),
            (r"^len\((.+)\)$", "jovaString.len({})"),
            (r"^sub\((.+),\s*(\d+),\s*(\d+)\)$", "jovaString.sub({}, {}, {})"),
            (r"^replace\((.+),\s*(.+),\s*(.+)\)$", "jovaString.replace({}, {}, {})"),
            (r"^trim\((.+)\)$", "jovaString.trim({})"),
            (r"^split\((.+),\s*(.+)\)$", "jovaString.split({}, {})"),
            (r"^at\((.+),\s*(\d+)\)$", "jovaString.at({}, {})"),
        ];
        for (pattern, template) in patterns {
            let re = Regex::new(pattern).unwrap();
            if let Some(caps) = re.captures(ops) {
                let mut args = Vec::new();
                for i in 1..caps.len() {
                    let arg = caps[i].trim();
                    if arg.parse::<i64>().is_ok() || arg.parse::<f64>().is_ok() {
                        args.push(arg.to_string());
                    } else {
                        args.push(self.transform_expression(arg));
                    }
                }
                let mut result = template.to_string();
                for (i, arg) in args.iter().enumerate() {
                    result = result.replace(&format!("{{{}}}", i), arg);
                }
                return result;
            }
        }
        format!("\"{}\"", ops.replace('\\', "\\\\").replace('"', "\\\""))
    }

    pub fn get_modules(&self) -> String {
        format!("{:?}", self.modules.keys().collect::<Vec<_>>())
    }

    pub fn get_exports(&self) -> String {
        format!("{:?}", self.exports)
    }
}

impl Default for JovaCompiler {
    fn default() -> Self {
        Self::new()
    }
}
